-- RUN_2026-07-31_preflight.sql
-- Results from preflight.sql. Run 2026-07-31. Window: events 2025-08-01 to 2026-08-01,
-- MASTER load_tm >= 2025-05-01.
--
-- Three of four probes came back bad. The extraction cannot be trusted as written.
--
-- =========================================================================================
-- P1. MASTER GRAIN -- FAILED. This is a blocker.
-- =========================================================================================
-- max_rows_per_key = 95,014
-- keys_checked     = 385,665,736
--
-- MASTER is NOT one row per (consumer_id_hashed, TREATMENT_ID). The assumption in
-- UNSUB_TRACKING_KNOWLEDGE.md:137 ("believed... grain NOT yet verified") is false.
--
-- Scale of the damage, from P4's row count: 432,925,102 rows over 385,665,736 keys = 1.123
-- rows per key on AVERAGE. So the typical inflation is ~12%, not 95,014x -- the max is a
-- pathological key, almost certainly a null or sentinel consumer_id_hashed rather than a real
-- client. Both problems are real and they are different problems:
--   - the ~12% average fan-out inflates every COUNT and SUM in all three pulls
--   - the 95,014-row key would land ~95K duplicate rows for a single join match
--
-- Open question before the fix is safe: do the duplicate rows carry the SAME CLNT_NO (then
-- SELECT DISTINCT consumer_id_hashed, TREATMENT_ID, CLNT_NO resolves it cleanly) or DIFFERENT
-- CLNT_NOs (then one email maps to several clients and the attribution itself is ambiguous)?
-- preflight2.sql answers this.
--
-- =========================================================================================
-- P2. ZERO-MARGIN load_tm FILTER -- CONFIRMED, and large.
-- =========================================================================================
-- unsub_events_dropped_by_zero_margin = 178,184
--
-- The old filter silently deleted 178,184 unsub events -- unsubs that happened inside the window
-- whose MASTER row loaded before it. Consistent with the lag finding: 28.5% of unsubs land more
-- than 30 days after their send. Already fixed via MASTER_FLOOR = 2025-05-01 (3-month lookback).
--
-- =========================================================================================
-- P3. SEND ROWS DOUBLE COUNTED -- CONFIRMED.
-- =========================================================================================
-- client_treatments_with_multiple_send_rows = 8,084,229
--
-- 8.08M (client, treatment) pairs carry more than one distinct cd=1 timestamp. Since n_emails_*
-- sums cd=1 rows, email volume is overstated everywhere it appears -- which is the entire basis
-- of the contact-frequency cube and the dose-response reading.
-- UNSUB_TRACKING_KNOWLEDGE.md warns against counting raw rows without collapsing to send-journey
-- grain first. This is that warning coming true.
-- NOT YET FIXED.
--
-- =========================================================================================
-- P4. NULL / NEGATIVE CLNT_NO
-- =========================================================================================
-- null_clnt_no     = 16,519,813
-- negative_clnt_no = 0
-- rows_checked     = 432,925,102
--
-- No negative client numbers, so the MOD(ABS(...)) change was harmless but unnecessary.
-- 16.5M rows (3.8%) carry a NULL CLNT_NO. MOD(NULL, 10) matches no bite, so these drop out of the
-- two bitten pulls but are still counted by the unbitten Pull B. That alone breaks reconciliation
-- between q_mne and the cubes. They also cannot be joined to UCP, so they are unusable for any
-- client-level measure -- but they must be dropped EXPLICITLY and reported, not lost silently in
-- a MOD expression.
-- NOT YET FIXED.
--
-- =========================================================================================
-- WHAT THIS MEANS
-- =========================================================================================
-- Every count produced by this pipeline before today was inflated by MASTER fan-out (~12%
-- typical), inflated again by duplicate send rows, and undercounted leavers by 178,184 events
-- from the load_tm filter. The errors run in both directions, so they do not cancel and the net
-- bias is not predictable from these numbers alone.
--
-- Nothing produced by spotlight.py before this run should be quoted.


-- =========================================================================================
-- preflight2.sql RESULTS. Run 2026-07-31. These settled the P1 blocker.
-- =========================================================================================
--
-- P5. Shape of the MASTER fan-out
-- rows_per_key      | keys        | total_rows
-- 1 row (clean)     | 360,378,371 | 360,378,371
-- 2 rows            |  18,787,132 |  37,574,264
-- 3-5 rows          |   4,820,618 |  17,390,888
-- 6-20 rows         |   1,615,359 |  13,729,928
-- 21-100 rows       |      60,256 |   1,956,910
-- over 100 rows     |       4,000 |   1,894,741
-- TOTAL             | 385,665,736 | 432,925,102
--
-- 93.4% of keys are already clean. Excess is 47,259,366 rows = 10.9% inflation, matching the
-- 1.123 rows-per-key average. Not a structural problem - a long tail.
--
-- P6. THE DECIDER - do duplicates carry the same client?
-- 1 client (pure duplication)  | 376,129,145   (97.5%)
-- 3-5 clients (AMBIGUOUS)      |   9,536,591
--
-- CAVEAT: the query's CASE had a hole - c = 0 falls through to 'c <= 5' and is labelled
-- "3-5 clients". P7 shows the worst keys have distinct_clients = 0, so that second bucket is
-- mostly NULL-client junk, not genuine multi-client ambiguity. The real ambiguous share is
-- smaller than 9.5M and was not separately measured.
--
-- Verdict: duplication, not ambiguity. SELECT DISTINCT on the MASTER side resolves it.
--
-- P7. What the pathological keys actually are
-- TREATMENT_ID | rows_for_key | distinct_clients | min/max CLNT_NO
-- 2024313BBP   |       95,014 |        0         | null / null
-- 2024313BBP   |       58,457 |        0         | null / null
-- CABVRSN1     |        7,310 |        0         | null / null
-- DEFAULT      |        5,064 |        1         | 414574160
-- DEFAULT      |        4,733 |        1         | 128841087
-- DEFAULT      |        4,347 |        1         | 279734628
-- 2024313BBP   |        4,200 |        0         | null / null   (x4 more keys)
--
-- The monsters are NULL-client rows under junk TREATMENT_IDs. 'DEFAULT' and 'CABVRSN1' are not
-- deployment identifiers at all, so SUBSTR(TREATMENT_ID, 8, 3) on them yields no valid MNE.
-- Filtering CLNT_NO IS NOT NULL removes them.
--
-- P8. FAILED - 3662, "Concatenation between BYTE data and other types is illegal".
-- consumer_id_hashed is a BYTE column and cannot be concatenated. Not re-run: P1 and P4 already
-- give both numbers it was going to produce (385,665,736 keys, 432,925,102 rows).
--
-- =========================================================================================
-- FIXES APPLIED (spotlight.py, SCHEMA_VERSION 4)
-- =========================================================================================
-- 1. MASTER joined as SELECT DISTINCT consumer_id_hashed, TREATMENT_ID, CLNT_NO
--    WHERE CLNT_NO IS NOT NULL. Removes the 10.9% fan-out and the junk keys.
-- 2. EVENT collapsed to one row per (client, treatment, disposition) with MIN(timestamp).
--    Removes retry rows from email volume.
-- 3. MASTER_FLOOR set 3 months before WIN_FLOOR. Recovers the 178,184 deleted unsub events.
-- 4. WIN_CEIL added so pulls run at different times still cover the same window.
